(* open Tick *)
(* open Core *)

(* let () = *)
(*   let tokens = [ Token.IntLiteral 5; Token.Plus; Token.IntLiteral 6 ] in *)
(*   match Precparser.expression Precparser.Min tokens with *)
(*   | None -> failwith "Failed to parse" *)
(*   | Some ((expr, _prec), rest) -> *)
(*     print_endline @@ Ast.show_expression expr; *)
(*     if List.length rest = 0 *)
(*     then print_endline "\nNo remaining tokens" *)
(*     else print_endline "\nRemaining tokens:"; *)
(*     List.map rest ~f:Token.show |> List.iter ~f:print_endline |> ignore *)
(* ;; *)
